use std::error::Error;

pub enum WeatherIcon {
    Cloudy,
    CloudyAlert,
    Dust,
    Fog,
    Hail,
    Hazy,
    Hurricane,
    Lightning,
    LightningRainy,
    Night,
    NightPartlyCloudy,
    PartlyCloudy,
    PartlyLightning,
    PartlyRainy,
    PartlySnowy,
    PartlySnowyRainy,
    Pouring,
    Rainy,
    Snowy,
    SnowyHeavy,
    SnowyRainy,
    Sunny,
    SunnyAlert,
    Tornado,
    Windy,
}

impl TryFrom<u8> for WeatherIcon {
    type Error = String;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Sunny),
            1 => Ok(Self::Sunny),
            2 => Ok(Self::PartlyCloudy),
            3 => Ok(Self::PartlyCloudy),
            4 => Ok(Self::PartlyCloudy),
            5 => Ok(Self::PartlyCloudy),
            6 => Ok(Self::PartlyRainy),
            7 => Ok(Self::PartlySnowyRainy),
            8 => Ok(Self::PartlySnowy),
            9 => Ok(Self::PartlyLightning),
            10 => Ok(Self::Cloudy),
            11 => Ok(Self::Rainy),
            12 => Ok(Self::Rainy),
            13 => Ok(Self::Pouring),
            14 => Ok(Self::Rainy),
            15 => Ok(Self::SnowyRainy),
            16 => Ok(Self::Snowy),
            17 => Ok(Self::Snowy),
            18 => Ok(Self::SnowyHeavy),
            19 => Ok(Self::LightningRainy),
            22 => Ok(Self::PartlyCloudy),
            23 => Ok(Self::Hazy),
            24 => Ok(Self::Fog),
            25 => Ok(Self::Snowy),
            26 => Ok(Self::Snowy),
            27 => Ok(Self::Hail),
            28 => Ok(Self::SnowyRainy),
            29 => Ok(Self::Night),
            30 => Ok(Self::Night),
            31 => Ok(Self::Night),
            32 => Ok(Self::NightPartlyCloudy),
            33 => Ok(Self::NightPartlyCloudy),
            34 => Ok(Self::NightPartlyCloudy),
            35 => Ok(Self::NightPartlyCloudy),
            36 => Ok(Self::PartlyRainy),
            37 => Ok(Self::PartlySnowyRainy),
            38 => Ok(Self::PartlySnowy),
            39 => Ok(Self::LightningRainy),
            40 => Ok(Self::Windy),
            41 => Ok(Self::Tornado),
            42 => Ok(Self::Tornado),
            43 => Ok(Self::Dust),
            44 => Ok(Self::Dust),
            45 => Ok(Self::Dust),
            46 => Ok(Self::LightningRainy),
            47 => Ok(Self::LightningRainy),
            48 => Ok(Self::Tornado),
            _ => Err(format!("Unknown current weather icon value: {}", value)),
        }
    }
}

fn citypage_weather() -> Result<(), Box<dyn Error>> {
    unimplemented!()
}
