[package]
name = "kiiin_frame"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["multipart"] }
image = "0.25.6"
tokio = { version = "1.46.1", features = ["full"] }
